services:
  mongo:
    image: mongo
    container_name: capstone_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nerd
      - MONGO_INITDB_ROOT_PASSWORD=csci4308
    # -- Uncomment to persist data --
    # volumes:
    #   - ./mongodb_data:/data/db