version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD
  graphql-engine:
    image: hasura/graphql-engine:v2.13.2.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      - HASURA_GRAPHQL_METADATA_DATABASE_URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_AUTH_HOOK
    volumes:
    - ./project/migrations:/hasura-migrations
    - ./project/metadata:/hasura-metadata
  leeds2-auth:
    build: ./auth
    ports:
      - "4308:4308"
    environment:
      - GRAPHQL_ENDPOINT
      - AUTH_PORT