mutation merge_labels_globally($parent_label_id: bigint!, $child_label_id: bigint!) {
  update_document_label_many(updates: {where: {label_id: {_eq: $child_label_id}}, _set: {label_id: $parent_label_id}}) {
    affected_rows
  }
  update_snippets_many(updates: {where: {label_id: {_eq: $child_label_id}}, _set: {label_id: $parent_label_id}}) {
    affected_rows
  }
  delete_document_label(where: {label_id: {_eq: $child_label_id}}) {
    affected_rows
  }
}

mutation merge_labels_within_document($document_id: bigint!, $parent_label_id: bigint!, $child_label_id: bigint!) {
  update_document_label_many(updates: {where: {label_id: {_eq: $child_label_id}, document_id: {_eq: $document_id}}, _set: {label_id: $parent_label_id}}) {
    affected_rows
  }
  update_snippets_many(updates: {where: {label_id: {_eq: $child_label_id}, document_id: {_eq: $document_id}}, _set: {label_id: $parent_label_id}}) {
    affected_rows
  }
  delete_document_label(where: {label_id: {_eq: $child_label_id}, document_id: {_eq: $document_id}}) {
    affected_rows
  }
}

query documents_with_label($label_id: bigint!) {
  document_label(where: {label_id: {_eq: $label_id}}, distinct_on: document_id) {
    document {
      id
      title
    }
  }
}